name: Check Dependencies
on:
  push:
    branches: [development]

jobs:
  create-pull-request-gh:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Setup github
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16.10.0"

      - name: Setup gh
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

      - name: Update dependencies
        run: |
          npm install date-fns --save

      - name: Create Pull Request
        run: |
          git checkout -b update-dependencies
          git commit -am "[ASN-000] Update Dependencies"
          gh pr create --base master --head update-dependencies --title "The bug is fixed" --body "Everything works again"
